version: "3"

services:

  sosemu:

    image: smartemission/smartapp:latest

    container_name: smartapp

    restart: unless-stopped

    networks:
      - se_back

#    ports:
#      - 80:80

networks:
  se_back:
    external: true
