version: '3.1'

services:

  grafana:

    image: smartemission/se-grafana:5.1.3-2

    container_name: grafana

    environment:
      - SE_INFLUX_URL=http://influxdb:8086
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana

    env_file:
      # for other config vars (see Docker def README)
      - ../../etl/options/${HOSTNAME}.args

    labels:
      - "traefik.backend=grafana"
      - "traefik.enable=true"
      - "traefik.frontend.priority=500"
      - "traefik.frontend.rule=PathPrefixStrip:/grafana"
      - "traefik.docker.network=se_back"

    networks:
      - se_back

networks:
  se_back:
    external: true
