version: '3.1'

services:
  grafana:
    image: smartemission/se-grafana:latest
    # image: grafana/grafana:5.1.3

    container_name: grafana

    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana

    env_file:
      # for config vars (see Docker def)
      - ../../etl/options/${HOSTNAME}.args

    labels:
      - "traefik.backend=grafana"
      - "traefik.enable=true"
      - "traefik.frontend.priority=500"
      - "traefik.frontend.rule=PathPrefixStrip:/grafana"
      - "traefik.docker.network=se_back"

    networks:
      # Visible in SE backend and frontend Docker network
      - se_back

networks:
  se_back:
    external: true
