version: "3"

services:

  sosemu:
    # build: ./

    image: smartemission/se-sosemu:latest

    container_name: sosemu

    restart: unless-stopped

    labels:
      - "traefik.backend=sosemu"
      - "traefik.enable=true"
      - "traefik.frontend.priority=500"
      - "traefik.frontend.rule=PathPrefixStrip:/sosemu"
      - "traefik.frontend.headers.customRequestHeaders=X-Script-Name:/sosemu"
      - "traefik.docker.network=se_back"

    networks:
      - se_back

    env_file:
      # See https://github.com/gost/docs/blob/master/gost_configuration.md
      # for config vars
      - ../../etl/options/${HOSTNAME}.args

#    environment:
#      - SOSEMU_DB_NAME=thedb
#      - SOSEMU_DB_HOST=thedbhost
#      - SOSEMU_DB_PORT=thedbport
#      - SOSEMU_DB_SCHEMA=theschema
#      - SOSEMU_DB_USER=theuser
#      - SOSEMU_DB_PASSWORD=thepasswd

#    ports:
#      - 80:80

networks:
  se_back:
    external: true
