version: '3.1'

services:
  web:
    image: smartemission/apache2

    container_name: web

    labels:
      - "traefik.backend=web"
      - "traefik.enable=true"
      - "traefik.frontend.priority=10"
      - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.smartemission.nl;PathPrefixStrip:/"
      - "traefik.docker.network=se_front"

    networks:
      - se_front
      - se_back

    ports:
      - "80:80"
      
    volumes:
      - ./config/sites-enabled:/etc/apache2/sites-enabled
      - ./config/admin:/etc/apache2/admin
      - ./config/phppgadmin:/etc/phppgadmin
      - ./site:/var/web/site
      - ./api:/var/web/api
      - ./cgi-bin:/var/web/cgi-bin
      - /var/smartem/log/apache2:/var/log/apache2

networks:
  se_front:
    external: true
  se_back:
    external: true
