# See https://www.robustperception.io/sending-email-with-the-alertmanager-via-gmail/
route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: $GMAIL_ACCOUNT
    from: $GMAIL_ACCOUNT
    smarthost: smtp.gmail.com:587
    auth_username: "$GMAIL_ACCOUNT"
    auth_identity: "$GMAIL_ACCOUNT"
    auth_password: "$GMAIL_AUTH_TOKEN"

#route:
#    receiver: 'slack'
#
#receivers:
#    - name: 'slack'
#      slack_configs:
#          - send_resolved: true
#            username: '<username>'
#            channel: '#<channel-name>'
#            api_url: '<incomming-webhook-url>'
