version: "3"

services:

  admin:

    image: smartemission/se-admin:latest

    container_name: admin

    restart: unless-stopped

    labels:
      - "traefik.backend=admin"
      - "traefik.enable=true"
      - "traefik.frontend.priority=500"
      - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.smartemission.nl;PathPrefixStrip:/admin"
      - "traefik.docker.network=se_front"

    networks:
      - se_back
      - se_front

    ports:
      - 80:80

networks:
  se_front:
    external: true
  se_back:
    external: true
