version: "3"

services:

  admin:

    image: smartemission/se-admin:1.0.1

    container_name: admin

    restart: unless-stopped

    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/adm"
      - "traefik.backend=admin"
      - "traefik.enable=true"
      - "traefik.frontend.priority=100"
      - "traefik.frontend.headers.customRequestHeaders=X-Script-Name:/adm"
      - "traefik.frontend.auth.basic=sadmin:$$apr1$$gVo/HcPx$$2AudzGfyX7Xxg7aD/b1zf."
      - "traefik.docker.network=se_back"

    volumes:
      - /var/smartem/log/:/var/log/smartem

    networks:
      - se_back

#    ports:
#      - 80:80

networks:
  se_back:
    external: true
