version: '3.1'

services:
  proxy:
    image: traefik:1.5.3-alpine
    command: --docker --logLevel=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml

networks:
  webgateway:
    driver: bridge
