version: "3"

services:

  home:

    image: smartemission/se-home:1.0.0

    container_name: home

    restart: unless-stopped

    labels:
      - "traefik.backend=home"
      - "traefik.enable=true"
      - "traefik.frontend.priority=5"
      - "traefik.frontend.rule=PathPrefixStrip:/"
      - "traefik.docker.network=se_back"

    networks:
      - se_back

#    ports:
#      - 80:80

networks:
  se_back:
    external: true
