version: '3.1'

services:
  mosquitto:
    image: smartemission/se-mosquitto:latest

    container_name: mosquitto

    labels:
      - "traefik.enable=false"
#      - "traefik.backend=mosquitto"
#      - "traefik.frontend.priority=500"
#      - "traefik.frontend.rule=PathPrefixStrip:/mosquitto"
#      - "traefik.docker.network=se_back"

    expose:
     - "1883"
     - "9001"

    networks:
      - se_back

networks:
  se_back:
    external: true
