version: "3"

services:

  heron:

    image: smartemission/se-heron:1.0.3

    container_name: heron

    restart: unless-stopped

    labels:
      - "traefik.backend=heron"
      - "traefik.enable=true"
      - "traefik.frontend.priority=500"
      - "traefik.frontend.rule=PathPrefixStrip:/heron"
      - "traefik.frontend.headers.customRequestHeaders=X-Script-Name:/heron"
      - "traefik.docker.network=se_back"

    networks:
      - se_back

#    ports:
#      - 80:80

networks:
  se_back:
    external: true
