version: '3.1'

services:

  influxdb:

    # image: influxdb:1.4.2
    image: influxdb:1.6.1

    # Data Collector 1
    container_name: influxdb

    env_file:
      # Should set all influx_* DB-related vars
      - influxdb.env
      
    environment:
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
      - INFLUXDB_HTTP_AUTH_ENABLED=true

    labels:
      - "traefik.backend=influxdb"
      - "traefik.enable=true"
      - "traefik.frontend.priority=500"
      - "traefik.frontend.rule=PathPrefixStrip:/influxdb"
      - "traefik.docker.network=se_back"

    expose:
     - "8086"

    ports:
      - "8086:8086"

    networks:
      # Visible in SE backend and frontend Docker network
      - se_back

    volumes:
      - /private/var/smartem/data/influxdb:/var/lib/influxdb
      - /private/var/smartem/backup/influxdb:/backup

networks:
  se_back:
    external: true
