version: '3.1'

services:

  influxdb-dc1:

    # image: influxdb:1.4.2
    image: influxdb:1.5.3

    # Data Collector 1
    container_name: influxdb-dc1

    env_file:
      # Should set all influx_* DB-related vars
      - influxdb.env
      
    environment:
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
      - INFLUXDB_HTTP_AUTH_ENABLED=true

    labels:
      - "traefik.backend=influxdb-dc1"
      - "traefik.enable=true"
      - "traefik.frontend.priority=5000"
      - "traefik.frontend.rule=PathPrefixStrip:/influxdb-dc1"
      - "traefik.docker.network=se_back"

    expose:
     - "8086"

    ports:
      - "8086:8086"

    networks:
      # Visible in SE backend and frontend Docker network
      - se_back

    volumes:
      - /var/smartem/data/influxdb-dc1:/var/lib/influxdb
      - /var/smartem/backup/influxdb-dc1:/backup

networks:
  se_back:
    external: true
