version: '3.1'

services:
  gost:
    image: smartemission/se-gost:latest

    container_name: gost

    env_file:
      # See https://github.com/gost/docs/blob/master/gost_configuration.md
      # for config vars
      - ../../etl/options/${HOSTNAME}.args

      # Or set as env vars
      # GOST_SERVER_EXTERNAL_URI=http://<host>:[port]/gost
      # GOST_DB_HOST=postgis
      # GOST_DB_PORT=
      # GOST_DB_DATABASE=
      # GOST_DB_USER=
      # GOST_DB_PASSWORD=

    labels:
      - "traefik.backend=gost"
      - "traefik.enable=true"
      - "traefik.frontend.priority=500"
      - "traefik.frontend.rule=Method:GET"
      - "traefik.frontend.rule=PathPrefixStrip:/gost"
      - "traefik.docker.network=se_back"

    expose:
     - "8080"

    networks:
      - se_back

networks:
  se_back:
    external: true
