# Common variable values, see .env/.args files for host-specific values
server:
    name: GOST Server
    host: 0.0.0.0
    port: 8080
    clientContent: ./client/
    maxEntityResponse: 100
    indentedJson: true
    https: false
    httpsCert:
    httpsKey:
database:
    schema: v1
    ssl: false
    maxIdleConns: 10
    maxOpenConns: 20
mqtt:
    enabled: true
    host: mosquitto
    port: 1883
logger:
    fileName: /var/log/gost
    verbose: false
