server:
    name: GOST Server
    host: 0.0.0.0
    port: 8080
    externalUri: http://localhost:8080/
    clientContent: ./client/
    maxEntityResponse: 20
    indentedJson: true
    https: false
    httpsCert:
    httpsKey:
database:
    host: postgis
    port: 5432
    user: docker
    password: docker
    database: gis
    schema: v1
    ssl: false
    maxIdleConns: 10
    maxOpenConns: 20
mqtt:
    enabled: false
    host: localhost
    port: 1883
