version: "3"

services:

  waalkade:

    image: smartemission/se-waalkade:latest

    container_name: waalkade

    restart: unless-stopped

    labels:
      - "traefik.backend=waalkade"
      - "traefik.enable=true"
      - "traefik.frontend.priority=500"
      - "traefik.frontend.rule=PathPrefixStrip:/waalkade"
      - "traefik.frontend.headers.customRequestHeaders=X-Script-Name:/waalkade"
      - "traefik.docker.network=se_front"

    networks:
      - se_back
      - se_front

#    ports:
#      - 80:80

networks:
  se_front:
    external: true
  se_back:
    external: true
