version: "3"

services:

  waalkade:

    image: smartemission/se-waalkade:1.0.0

    container_name: waalkade

    restart: unless-stopped

    labels:
      - "traefik.backend=waalkade"
      - "traefik.enable=true"
      - "traefik.frontend.priority=500"
      - "traefik.frontend.rule=Host: pdok.smartemission.nl,test.smartemission.nl;PathPrefix:/waalkade"
      - "traefik.docker.network=se_back"

    networks:
      - se_back

#    ports:
#      - 80:80

networks:
  se_back:
    external: true
