# Adapted from Brian Christner's: https://github.com/vegasbrianc/prometheus
# All credits there!
# Taken version-2 branch on dec 18, 2017.
#
# Changes by Just van den Broecke:
# - removed Docker Swarm stuff (why needed?)
# - removed port mappings (prevent outside access)
# - run on local bridge network  (network_mode: bridge, as to be proxied from Apache web container)

version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

#networks:
#  front-tier:
#  back-tier:

services:

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    links:
      - prometheus:prometheus
#    ports:
#      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - grafana/grafana.conf
    network_mode: bridge
#    networks:
#      - back-tier
#      - front-tier

  prometheus:
    # image: prom/prometheus:v2.0.0
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - "--web.external-url=http://${se_host}${se_port}/adm/prometheus"
      # - '--web.route-prefix=/prometheus'

    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
      - node-exporter
      
    network_mode: bridge
#    networks:
#      - back-tier
    restart: always
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == moby

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    network_mode: bridge
#    networks:
#      - back-tier
    restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == moby

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    network_mode: bridge
#    networks:
#      - back-tier
    restart: always
#    deploy:
#      mode: global

  cadvisor:
    # image: google/cadvisor
    image: geonovum/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
#    ports:
#      - 8080:8080
    network_mode: bridge
#    networks:
#      - back-tier
    restart: always
#    deploy:
#      mode: global

